.TH "Actuator" 3 "Fri Mar 23 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Actuator \- A general class for external loads\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actuator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActuator\fP (short GPIO)"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "virtual void \fBinitialise\fP ()"
.br
.RI "Initialisation procedure with the wiringPi library\&. "
.ti -1c
.RI "void \fBswitchOn\fP ()"
.br
.RI "Sets the value of the pin to HIGH\&. "
.ti -1c
.RI "void \fBswitchOff\fP ()"
.br
.RI "Sets the value of the pin to LOW\&. "
.in -1c
.SH "Detailed Description"
.PP 
A general class for external loads\&. 

This class merely allows the HIGH/LOW switching of pins ideal for external loads connected through logic-level MOSFETs/transistor\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Actuator::Actuator (short GPIO)"

.PP
Class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGPIO\fP Raspberry pi pin connected to the actuator\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
