.TH "ControllerThread" 3 "Fri Mar 23 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ControllerThread
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCppThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControllerThread\fP ()"
.br
.RI "Class constructor\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
