.TH "CppThread" 3 "Fri Mar 23 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CppThread \- GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CppThread\&.h>\fP
.PP
Inherited by \fBControllerThread\fP, and \fBWebThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP ()"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007\&. 

(C) 2018, Bernd Porr mail@bernporr.me.uk 

.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
