.TH "CppTimer" 3 "Fri Mar 23 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CppTimer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBrewTimer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP (long nanosecs)"
.br
.ti -1c
.RI "virtual void \fBtimerEvent\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
