.TH "md_README" 3 "Fri Mar 23 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- README 

.PP
.SH "Description"
.PP
.PP
Excellentea is an automatic tea maker\&. The user can operate the machine remotely through an online interface\&. In other words, you can order your tea, by chosing from several modes, as you leave work and find it ready when you get home\&. It also comes with the option of controlling the machine using control buttons and an LCD display\&.
.PP
.SH "Usage"
.PP
.PP
.SS "Installation"
.PP
Clone the repository to your Raspberry Pi and run the following commands:
.PP
.PP
.nf
\&./configure
make
make install
.fi
.PP
 The program can then be started by running the command
.PP
.PP
.nf
excellentea
.fi
.PP
 from the terminal\&.
.PP
.SS "User operation"
.PP
.IP "1." 4
Load your cup with water
.IP "2." 4
Load your tea infuser with the tea of your choice
.IP "3." 4
Activate the tea maker from the online user interface
.IP "4." 4
Choose the brewing mode of your tea
.IP "5." 4
Wait\&.\&.\&.tea is ready:)
.PP
.PP
.SH "Hardware"
.PP
.PP
.SS "Key components"
.PP
.IP "\(bu" 2
1 Raspberry PI microcontroller board (tested on version 3 Model B)
.IP "\(bu" 2
1 \fBStepper\fP motor (MIKROE-1530)
.IP "\(bu" 2
1 Digital temperature sensor (ds18b20)
.IP "\(bu" 2
12V DC power supply
.IP "\(bu" 2
1 heating element (12V) (B004O8BGXE)
.IP "\(bu" 2
1 tea infuser
.IP "\(bu" 2
1 reed float sensor (59630)
.IP "\(bu" 2
2 18-pin through hole socket (ED18DT)
.IP "\(bu" 2
2 Darlington transistor array (ULN2803A)
.IP "\(bu" 2
LCD
.IP "\(bu" 2
2 N-channel logic-level MOSFET (FQP30N06L)
.IP "\(bu" 2
MOSFET heat sink (507222B00000G)
.PP
.PP
.SS "Additional components"
.PP
The project also requires standard passive components (e\&.g\&. resistors), prototyping tools (e\&.g\&. breadboard/pcb) and materials for the encasing\&. See the \fCcircuit schematics\fP for details\&.
.PP
.SS "Protocol"
.PP
The digital temperature sensor \fBDS18B20\fP communicates with the board through a 1-wire protocol on pin 7 (BCM4)\&. The reed float sensor only outputs two-states so a communication protocol is not required\&.
.PP
.SS "Prerequisites"
.PP
The raspberry PI must be connected to the internet for remote access\&.
.PP
.SH "Software"
.PP
.PP
.SS "Flow diagram"
.PP
.PP
.SH "Authors"
.PP
.PP
.IP "\(bu" 2
\fC\fBAndrea Spanou\fP\fP - \fIInitial work\fP
.IP "\(bu" 2
\fC\fBCiaran McGeady\fP\fP - \fIInitial work\fP
.IP "\(bu" 2
\fC\fBSimone Marcigaglia\fP\fP - \fIInitial work\fP
.PP
.PP
See also the list of \fCcontributors\fP who participated in this project\&.
.PP
.SH "Contributing"
.PP
.PP
Please read \fBCONTRIBUTING\&.md\fP for details on our code of conduct, and the process for submitting pull requests to us\&.
.PP
.SH "License"
.PP
.PP
This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details\&.
.PP
.SH "Acknowledgments"
.PP
.PP
We would like to thank the weather in Glasgow for making us think about tea all the time\&. 
