.TH "sensor" 3 "Wed Mar 21 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor \- A general class for simple HIGH/LOW sensors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sensor\&.h>\fP
.PP
Inherited by \fBds18b20\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsensor\fP (short GPIO)"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "virtual void \fBinitialise\fP ()"
.br
.RI "Initialisation procedure with wiringPi library\&. "
.ti -1c
.RI "bool \fBreadStatus\fP ()"
.br
.RI "Reads boolean status of the sensor\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "short \fBpin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A general class for simple HIGH/LOW sensors\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sensor::sensor (short GPIO)"

.PP
Class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGPIO\fP Raspberry pi pin connected to the sensor\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
