.TH "stepper" 3 "Sat Mar 17 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stepper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBspin\fP (int speed, int revolutions, bool direction)"
.br
.ti -1c
.RI "\fBstepper\fP (short A1, short A2, short B1, short B2, int steps)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
