.TH "tea" 3 "Wed Mar 21 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tea \- A class defining a type of tea by its brewing time and temperature\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tea\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtea\fP (double brew_temp, double brew_time)"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "void \fBsetBrewTemperature\fP (double temp)"
.br
.RI "Set the brewing temperature\&. "
.ti -1c
.RI "void \fBsetBrewTime\fP (double time)"
.br
.RI "Set the brewing time\&. "
.ti -1c
.RI "double \fBgetBrewTemperature\fP ()"
.br
.ti -1c
.RI "double \fBgetBrewTime\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class defining a type of tea by its brewing time and temperature\&. 

Define a tea object in the context of Excellentea in terms of its brewing time and temperature\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tea::tea (double brew_temp, double brew_time)"

.PP
Class constructor\&. Create a tea object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbrew_temp\fP Brewing temperature in °C\&. 
.br
\fIbrew_time\fP Brewing time in minutes\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void tea::setBrewTemperature (double temp)"

.PP
Set the brewing temperature\&. 
.PP
\fBParameters:\fP
.RS 4
\fItemp\fP Brewing temperature in °C\&. 
.RE
.PP

.SS "void tea::setBrewTime (double time)"

.PP
Set the brewing time\&. 
.PP
\fBParameters:\fP
.RS 4
\fItime\fP Brewing time in minutes\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
