.TH "WebThread" 3 "Fri Mar 23 2018" "Version 1.0" "Excellentea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebThread \- A thread that handles the web interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WebThread\&.h>\fP
.PP
Inherits \fBCppThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWebThread\fP ()"
.br
.RI "Class constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
A thread that handles the web interface\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Excellentea from the source code\&.
